blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Community Discussions
    url: https://github.com/orgs/Cozymori/discussions
    about: Please ask and answer questions in our community discussions.
  - name: ğŸ“š Documentation
    url: https://github.com/Cozymori/.github/wiki
    about: Check our documentation for guides and references.
  - name: âœ‰ï¸ Email Support
    url: mailto:luv.wlgjs@jj.ac.kr
    about: Contact us directly for sensitive matters.